# Render Blueprint for PCO Arrivals Billboard
# This file defines the deployment configuration for the full-stack application
services:
  - type: web
    name: pco-arrivals-billboard
    runtime: node
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    # Health check configuration
    healthCheckPath: /api/auth-status
    # Auto-deploy on push to main branch
    autoDeploy: true 