services:
  - type: web
    name: pco-arrivals-billboard
    env: node
    buildCommand: npm run install:all
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
    buildFilter:
      paths:
        - client/**
        - server/**
        - package.json
        - package-lock.json 