# Render configuration for PCO Arrivals Billboard
# This file configures the build and deployment process
services:
  - type: web
    name: pco-arrivals-billboard
    env: node
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production 