# Render Blueprint for PCO Arrivals Billboard
# This file defines separate services for client and server
services:
  # React Frontend Service
  - type: web
    name: pco-arrivals-client
    runtime: node
    rootDir: client
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    # Health check configuration
    healthCheckPath: /
    # Auto-deploy on push to main branch
    autoDeploy: true

  # Node.js Backend Service
  - type: web
    name: pco-arrivals-server
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    # Health check configuration
    healthCheckPath: /api/auth-status
    # Auto-deploy on push to main branch
    autoDeploy: true 