//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Hand-maintained for the stub; the
//     designer will regenerate fields as controls are added in later phases.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.gracefellowship.Arrivals.Blocks
{
    using System.Web.UI.WebControls;

    /// <summary>
    /// Designer partial for ArrivalsAdmin. Control fields are added here as the
    /// markup grows. The UpdatePanel and NotificationBox are currently accessed
    /// only via markup, so no fields are required yet.
    /// </summary>
    public partial class ArrivalsAdmin
    {
    }
}
