//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Hand-maintained to match the .ascx
//     markup — the field IDs MUST exactly match the ID="..." attributes in the
//     .ascx or WebForms throws a "does not exist in current context" error.
//     (GLM-5.2: name drift between markup and designer is the #1 cause of failed
//      first builds. Keep these in sync.)
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated by Visual Studio.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.gracefellowship.Arrivals.Blocks
{
    using System.Web.UI;
    using System.Web.UI.HtmlControls;
    using System.Web.UI.WebControls;
    using Rock.Web.UI.Controls;

    /// <summary>
    /// Designer partial for ArrivalsAdmin. Declares every control that appears in
    /// ArrivalsAdmin.ascx with runat="server". The .ascx.cs partial must NOT
    /// redeclare these (would cause "member already defined").
    /// </summary>
    public partial class ArrivalsAdmin
    {
        // ─── UpdatePanel ──────────────────────────────────────────────────
        protected global::System.Web.UI.UpdatePanel upMain;

        // ─── Active session banner ────────────────────────────────────────
        protected global::System.Web.UI.WebControls.Panel pnlActiveSession;
        protected global::System.Web.UI.WebControls.Literal litActiveGroupType;
        protected global::System.Web.UI.WebControls.Literal litActiveDate;
        protected global::System.Web.UI.WebControls.Literal litActiveStartedBy;
        protected global::System.Web.UI.WebControls.HyperLink hlBillboard;
        protected global::System.Web.UI.WebControls.LinkButton lbClearSession;

        // ─── Configuration panel ──────────────────────────────────────────
        protected global::System.Web.UI.WebControls.Panel pnlConfig;
        protected global::System.Web.UI.WebControls.Literal litPanelTitle;
        protected global::Rock.Web.UI.Controls.NotificationBox nbMessage;
        protected global::Rock.Web.UI.Controls.DatePicker dpDate;
        protected global::Rock.Web.UI.Controls.RockDropDownList ddlGroupType;
        protected global::System.Web.UI.WebControls.LinkButton lbLaunch;

        // ─── Quick links ──────────────────────────────────────────────────
        protected global::System.Web.UI.WebControls.HyperLink hlKiosk;
        protected global::System.Web.UI.WebControls.HyperLink hlLocationStatus;
    }
}
