//------------------------------------------------------------------------------
// <auto-generated>
//     Hand-maintained to match Billboard.ascx markup. Field IDs MUST match the
//     ID="..." attributes in the .ascx exactly. Keep in sync.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.gracefellowship.Arrivals.Blocks
{
    using System.Web.UI.WebControls;

    /// <summary>
    /// Designer partial for Billboard. The billboard markup is mostly static HTML + client
    /// JS; only two server controls (the hidden fields carrying the poll URL and session flag).
    /// Do not redeclare these in .ascx.cs.
    /// </summary>
    public partial class Billboard
    {
        protected global::System.Web.UI.WebControls.HiddenField hfPollUrl;
        protected global::System.Web.UI.WebControls.HiddenField hfHasSession;
    }
}
