//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Hand-maintained for the stub; the
//     designer will regenerate fields as controls are added in later phases.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.gracefellowship.Arrivals.Blocks
{
    /// <summary>Designer partial for SecurityCodeEntry. No control fields needed yet.</summary>
    public partial class SecurityCodeEntry
    {
    }
}
