//------------------------------------------------------------------------------
// <auto-generated>
//     Hand-maintained to match SecurityCodeEntry.ascx markup. Field IDs MUST
//     match the ID="..." attributes in the .ascx exactly. Keep in sync.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.gracefellowship.Arrivals.Blocks
{
    using System.Web.UI.WebControls;
    using Rock.Web.UI.Controls;

    /// <summary>Designer partial for SecurityCodeEntry. Do not redeclare these in .ascx.cs.</summary>
    public partial class SecurityCodeEntry
    {
        protected global::System.Web.UI.UpdatePanel upKiosk;

        // No-session panel
        protected global::System.Web.UI.WebControls.Panel pnlNoSession;

        // Kiosk form
        protected global::System.Web.UI.WebControls.Panel pnlKiosk;
        protected global::System.Web.UI.WebControls.Literal litSessionHeader;
        protected global::Rock.Web.UI.Controls.NotificationBox nbResult;
        protected global::System.Web.UI.WebControls.TextBox tbSecurityCode;
        protected global::System.Web.UI.WebControls.Button btnSubmit;
        protected global::System.Web.UI.WebControls.Literal litSessionFooter;
    }
}
